# Generated by Django 4.1 on 2022-08-14 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlmap',
            name='url',
            field=models.CharField(max_length=100000000),
        ),
        migrations.AlterField(
            model_name='urlmap',
            name='urlShorten',
            field=models.CharField(max_length=100),
        ),
    ]
